# Site settings
title: Project Hacks
subtitle: on github Pages
email: hoezhanhui@gmail.com
description: A blog about dev projects & //TODO's
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projecthacks.xyz" # the base hostname & protocol for your site
author: Zhan Hui
street_address:
city: Madison
state: WI
zip_code: 53706
country: United States of America
phone: (608) 504-2226

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/E-Mech
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/zhanhuihoe
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
